import { StyleSheet } from "react-native";

import { palette, radius, screenEdgeGlassBleed, spacing } from "@/theme/tokens";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.ink,
  },
  loadingSafeArea: {
    flex: 1,
    backgroundColor: palette.ink,
  },
  loadingState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    padding: spacing.xl,
  },
  loadingTitle: {
    color: palette.sand,
    fontSize: 22,
    fontWeight: "800",
  },
  loadingText: {
    color: palette.mist,
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
  },
  mapOverlaySafeArea: {
    ...StyleSheet.absoluteFillObject,
  },
  mapTopBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: spacing.lg,
    paddingTop: 10,
  },
  mapTopStack: {
    gap: 10,
    alignItems: "center",
    width: 56,
  },
  mapBrandWrap: {
    position: "absolute",
    left: 0,
    bottom: spacing.xxl + 88,
  },
  circleButtonPressed: {
    transform: [{ scale: 0.97 }],
  },
  avatarButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#08110E",
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  avatarButtonSurface: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 28,
  },
  topBanner: {
    alignSelf: "center",
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: radius.pill,
    overflow: "hidden",
  },
  topBannerSurface: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: radius.pill,
  },
  topBannerText: {
    color: palette.sand,
    fontSize: 11,
    fontWeight: "600",
  },
  gamesSheet: {
    position: "absolute",
    left: spacing.sm,
    right: spacing.sm,
    overflow: "visible",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    shadowColor: "#050907",
    shadowOpacity: 0.28,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -6 },
    elevation: 18,
  },
  pastMeetupsToggleButton: {
    alignSelf: "flex-end",
  },
  pastMeetupsToggleLabel: {
    color: palette.parchment,
    fontSize: 12,
    fontWeight: "800",
  },
  gamesSheetContent: {
    flex: 1,
    minHeight: 0,
  },
  gamesSheetSectionAnimated: {
    flex: 1,
    minHeight: 0,
  },
  listCard: {
    backgroundColor: palette.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.line,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  listCardSelected: {
    borderColor: palette.ember,
  },
  listCardOverdue: {
    backgroundColor: "rgba(112, 46, 56, 0.22)",
    borderColor: "rgba(216, 108, 114, 0.44)",
  },
  listCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  listHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  listTitle: {
    color: palette.sand,
    fontSize: 17,
    fontWeight: "700",
  },
  listMeta: {
    color: palette.pine,
    fontSize: 13,
  },
  listMetaOverdue: {
    color: "#F3B0AE",
  },
  listBody: {
    color: palette.sand,
    fontSize: 14,
    lineHeight: 20,
  },
  listLocationText: {
    color: palette.mist,
    fontSize: 12,
    lineHeight: 17,
  },
  listSubtle: {
    color: palette.mist,
    fontSize: 13,
    lineHeight: 18,
  },
  listActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  listActionPrimaryCell: {
    flex: 1,
    minWidth: 0,
  },
  rowActions: {
    flexDirection: "row",
    gap: spacing.sm,
    flexWrap: "wrap",
  },
  manageStatusActions: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  inlineTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  metaTag: {
    minHeight: 28,
    borderRadius: radius.pill,
    backgroundColor: "rgba(231,216,188,0.14)",
    paddingHorizontal: spacing.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  metaTagLabel: {
    color: palette.sand,
    fontSize: 11,
    fontWeight: "700",
  },
  rowActionCell: {
    flex: 1,
    minWidth: 132,
  },
  inlineConfirmWrap: {
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  utilityActionButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: "rgba(255,255,255,0.02)",
    alignItems: "center",
    justifyContent: "center",
  },
  utilityActionButtonActive: {
    borderColor: palette.ember,
    backgroundColor: "rgba(241,143,92,0.12)",
  },
  dropdownDetailText: {
    color: palette.mist,
    fontSize: 13,
    lineHeight: 19,
  },
  dropdownDetailValue: {
    color: palette.sand,
    fontWeight: "700",
  },
  meetupInfoStack: {
    gap: spacing.xs,
  },
  meetupInfoLine: {
    gap: 4,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: "rgba(231,216,188,0.1)",
    backgroundColor: "rgba(255,255,255,0.03)",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  meetupInfoLabel: {
    color: palette.pine,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  meetupInfoValue: {
    color: palette.sand,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  meetupParticipationCard: {
    gap: spacing.xs,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: "rgba(241,143,92,0.32)",
    backgroundColor: "rgba(241,143,92,0.12)",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  meetupParticipationCardMuted: {
    gap: spacing.xs,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: "rgba(231,216,188,0.14)",
    backgroundColor: "rgba(255,255,255,0.04)",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  meetupParticipationTitle: {
    color: palette.sand,
    fontSize: 13,
    fontWeight: "700",
  },
  meetupParticipationBody: {
    color: palette.mist,
    fontSize: 12,
    lineHeight: 17,
  },
  meetupInfoActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  venueTag: {
    alignSelf: "flex-start",
    minHeight: 30,
    borderRadius: radius.pill,
    backgroundColor: "rgba(231,216,188,0.14)",
    paddingHorizontal: spacing.sm,
    paddingVertical: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  venueTagLabel: {
    color: palette.sand,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    textAlign: "center",
  },
  detailTitle: {
    color: palette.sand,
    fontSize: 20,
    fontWeight: "800",
  },
  detailBody: {
    color: palette.sand,
    fontSize: 14,
    lineHeight: 20,
  },
  supportingText: {
    color: palette.mist,
    fontSize: 13,
    lineHeight: 18,
  },
  linkTextInline: {
    color: palette.ember,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  inlinePressed: {
    opacity: 0.84,
  },
  sectionContent: {
    gap: spacing.sm,
  },
  capacityRow: {
    flexDirection: "row",
    gap: spacing.sm,
    alignItems: "center",
  },
  capacityInput: {
    flex: 1,
    minHeight: 46,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.chatBubble,
    paddingHorizontal: spacing.md,
    color: palette.sand,
    fontSize: 15,
  },
  pageSafeArea: {
    flex: 1,
    backgroundColor: "rgba(7,12,18,0.86)",
  },
  pageBackdropSurface: {
    position: "absolute",
    left: -screenEdgeGlassBleed,
    right: -screenEdgeGlassBleed,
    top: 0,
    bottom: 0,
    borderWidth: 0,
    backgroundColor: "rgba(26,44,62,0.3)",
  },
  chatPageSafeArea: {
    flex: 1,
    backgroundColor: "#0B0B0B",
  },
  pageLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
  },
  playerPageWrap: {
    flex: 1,
  },
  chatPageShell: {
    flex: 1,
    gap: spacing.md,
  },
  pageFooterPad: {
    paddingHorizontal: spacing.lg,
  },
  messageComposer: {
    gap: spacing.sm,
  },
  chatInput: {
    minHeight: 48,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.chatBubble,
    paddingHorizontal: spacing.md,
    color: palette.sand,
    fontSize: 15,
  },
  messageButton: {
    alignSelf: "flex-start",
    minWidth: 120,
  },
  notificationCard: {
    backgroundColor: palette.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.line,
    padding: spacing.lg,
    gap: spacing.xs,
  },
  notificationCardUnread: {
    borderColor: palette.ember,
  },
  notificationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  notificationKind: {
    color: palette.parchment,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  notificationTime: {
    color: palette.pine,
    fontSize: 12,
  },
  notificationTitle: {
    color: palette.sand,
    fontSize: 16,
    fontWeight: "700",
  },
  notificationBody: {
    color: palette.mist,
    fontSize: 14,
    lineHeight: 20,
  },
  accountHero: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
    backgroundColor: palette.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.line,
    padding: spacing.lg,
  },
  accountHeroCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  accountAvatarButton: {
    borderRadius: radius.pill,
  },
  accountName: {
    color: palette.sand,
    fontSize: 24,
    fontWeight: "800",
  },
  accountHandle: {
    color: palette.parchment,
    fontSize: 15,
    fontWeight: "700",
  },
  accountMeta: {
    color: palette.mist,
    fontSize: 13,
    lineHeight: 18,
    flexWrap: "wrap",
  },
  accountActionStack: {
    gap: spacing.sm,
  },
  infoPill: {
    minWidth: 140,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.card,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: 4,
  },
  infoPillLabel: {
    color: palette.pine,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  infoPillValue: {
    color: palette.sand,
    fontSize: 15,
    fontWeight: "700",
  },
  friendCard: {
    backgroundColor: palette.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.line,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  friendSubmenuButton: {
    minHeight: 64,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: "rgba(255,255,255,0.03)",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  friendSubmenuCopy: {
    flex: 1,
    gap: 2,
  },
  friendSubmenuTitle: {
    color: palette.sand,
    fontSize: 15,
    fontWeight: "700",
  },
  friendSubmenuMeta: {
    color: palette.mist,
    fontSize: 12,
    lineHeight: 17,
  },
  friendSubmenuTrailing: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  friendProfilePressable: {
    marginHorizontal: -spacing.xs,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
  },
  friendProfilePressableFlex: {
    flex: 1,
  },
  friendRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  friendRowBetween: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  friendCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  friendName: {
    color: palette.sand,
    fontSize: 16,
    fontWeight: "700",
  },
  friendMeta: {
    color: palette.pine,
    fontSize: 13,
  },
  friendStatusLine: {
    color: palette.mist,
    fontSize: 12,
  },
  friendIconActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  friendIconActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  friendMiniActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.ember,
    borderWidth: 1,
    borderColor: "rgba(241,143,92,0.24)",
  },
  friendMiniActionButtonGhost: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderColor: palette.line,
  },
  friendStatusPill: {
    minHeight: 34,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  friendStatusPillAccent: {
    backgroundColor: "rgba(241,143,92,0.18)",
    borderColor: "rgba(241,143,92,0.28)",
  },
  friendStatusPillNeutral: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderColor: palette.line,
  },
  friendStatusPillLabel: {
    color: palette.sand,
    fontSize: 12,
    fontWeight: "700",
  },
  publicProfileActions: {
    gap: spacing.sm,
  },
  publicProfileDualActions: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  listCardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  drawerButtonPressed: {
    opacity: 0.92,
  },
  modalLayer: {
    flex: 1,
    backgroundColor: "rgba(6,10,9,0.4)",
  },
  modalSafeArea: {
    flex: 1,
  },
  filterPanelWrap: {
    position: "absolute",
    left: spacing.md,
    right: spacing.md,
    alignItems: "flex-start",
  },
  filterCloseAnchor: {
    position: "absolute",
    left: spacing.md,
    zIndex: 2,
  },
  filterPanel: {
    width: "88%",
    maxWidth: 360,
    borderRadius: 28,
    backgroundColor: "rgba(18,18,18,0.98)",
    borderWidth: 1,
    borderColor: "rgba(231,216,188,0.12)",
    padding: spacing.lg,
    gap: spacing.md,
    overflow: "hidden",
  },
  filterScrollContent: {
    gap: spacing.xl,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
  },
  filterFormatGroup: {
    gap: spacing.sm,
  },
  filterFormatGroupTitle: {
    color: palette.parchment,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  filterDateField: {
    minHeight: 48,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.card,
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  filterDateFieldLabel: {
    flex: 1,
    color: palette.sand,
    fontSize: 14,
    fontWeight: "700",
  },
  filterCalendarOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-start",
    paddingTop: 128,
    paddingHorizontal: spacing.md,
  },
  filterCalendarHint: {
    color: palette.mist,
    fontSize: 13,
    lineHeight: 18,
  },
  filterRangeDay: {
    backgroundColor: "rgba(241,143,92,0.08)",
    borderColor: "rgba(241,143,92,0.16)",
  },
  overlayHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  overlayTitle: {
    color: palette.sand,
    fontSize: 22,
    fontWeight: "800",
  },
  overlaySubtitle: {
    color: palette.pine,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  overlayCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(231,216,188,0.1)",
  },
  sheetKeyboard: {
    flex: 1,
    justifyContent: "flex-end",
  },
  sheetSafeArea: {
    flex: 1,
    justifyContent: "flex-end",
  },
  sheetBodyKeyboard: {
    flex: 1,
    overflow: "visible",
  },
  sheet: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "rgba(18,18,18,0.98)",
    borderWidth: 1,
    borderColor: "rgba(231,216,188,0.12)",
    overflow: "visible",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.lg,
    gap: spacing.md,
  },
  sheetDragZone: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
  },
  sheetContent: {
    gap: spacing.md,
    paddingBottom: spacing.md,
    overflow: "visible",
  },
  composerDateTimeRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  composerSelectField: {
    flex: 1,
    minHeight: 82,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.chatBubble,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    gap: spacing.sm,
  },
  composerSelectLabel: {
    color: palette.pine,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  composerSelectValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  composerSelectValue: {
    flex: 1,
    color: palette.sand,
    fontSize: 15,
    fontWeight: "700",
  },
  addressFieldWrap: {
    gap: 8,
  },
  addressFieldWrapFocused: {
    position: "relative",
    zIndex: 120,
    elevation: 24,
  },
  addressFieldInput: {
    minHeight: 48,
    backgroundColor: palette.card,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.line,
    paddingHorizontal: spacing.md,
    color: palette.sand,
    fontSize: 15,
  },
  addressFieldTrigger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  addressFieldValue: {
    flex: 1,
    color: palette.sand,
    fontSize: 15,
    fontWeight: "600",
  },
  addressFieldPlaceholder: {
    flex: 1,
    color: palette.pine,
    fontSize: 15,
  },
  addressSearchModalRoot: {
    flex: 1,
    justifyContent: "flex-end",
  },
  addressSearchBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(6,10,9,0.45)",
  },
  addressSearchSheetWrap: {
    flex: 1,
    justifyContent: "flex-end",
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
  },
  addressSearchSheet: {
    maxHeight: "72%",
    borderRadius: 28,
    backgroundColor: "rgba(18,18,18,0.98)",
    borderWidth: 1,
    borderColor: "rgba(231,216,188,0.12)",
    padding: spacing.lg,
    gap: spacing.md,
  },
  overlayHeaderCopy: {
    flex: 1,
  },
  addressSearchInputWrap: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.card,
    paddingHorizontal: spacing.md,
  },
  addressSearchInput: {
    minHeight: 48,
    color: palette.sand,
    fontSize: 15,
  },
  addressSuggestionCard: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.card,
    overflow: "hidden",
    zIndex: 50,
    elevation: 18,
    shadowColor: "#020403",
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  addressSuggestionCardModal: {
    position: "relative",
    overflow: "hidden",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  addressSuggestionList: {
    paddingBottom: spacing.sm,
  },
  addressSuggestionLoading: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  addressSuggestionLoadingText: {
    color: palette.mist,
    fontSize: 13,
  },
  addressSuggestionRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: "rgba(231,216,188,0.08)",
  },
  addressSuggestionCopy: {
    flex: 1,
    gap: 2,
  },
  addressSuggestionTitle: {
    color: palette.sand,
    fontSize: 14,
    fontWeight: "700",
  },
  addressSuggestionSubtitle: {
    color: palette.mist,
    fontSize: 12,
    lineHeight: 17,
  },
  helperCard: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.chatBubble,
    padding: spacing.md,
    gap: 6,
  },
  helperCardTitle: {
    color: palette.parchment,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  helperCardBody: {
    color: palette.sand,
    fontSize: 14,
    lineHeight: 20,
  },
  statusChip: {
    minHeight: 30,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  statusChipCompact: {
    minHeight: 30,
  },
  statusChipOpen: {
    backgroundColor: "rgba(147, 184, 159, 0.2)",
  },
  statusChipFilled: {
    backgroundColor: "rgba(231, 216, 188, 0.18)",
  },
  statusChipConfirmed: {
    backgroundColor: "rgba(241, 143, 92, 0.22)",
  },
  statusChipClosed: {
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  statusChipCancelled: {
    backgroundColor: "rgba(147, 47, 47, 0.22)",
  },
  statusChipOverdue: {
    backgroundColor: "rgba(216, 108, 114, 0.24)",
  },
  statusChipLabel: {
    color: palette.sand,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    textAlign: "center",
  },
});
